### ISSUE TITLE
Error AccesKey not set in config

### ISSUE THREAD

**Issue by rdrgporto** [buehler/go-elastic-twitterbeat#3]
Hi,

I have compiled Twitterbeat with Go (in Linux), and when I execute :

`./twitterbeat -e -c twitterbeat.yml -d "*"`

I receive an error **"AccessKey was not set in config"**, however, I have written all keys from Twitter. I add log's output in order to you can see it:

```
2016/04/26 09:09:26.041438 filter.go:41: DBG  configuration []
2016/04/26 09:09:26.041628 filter.go:52: DBG  filters:
2016/04/26 09:09:26.041776 beat.go:203: DBG  Filters:
2016/04/26 09:09:26.041943 twitterbeat.go:47: INFO Loading configuration
2016/04/26 09:09:26.043919 beat.go:314: CRIT Exiting: Defaults could not be set: Mandatory field "AccessKey" was not set in config.
Exiting: Defaults could not be set: Mandatory field "AccessKey" was not set in config.
```

I have done a simple configuration in **twitterbeat.yml**:

```
twitterbeat:
Defines how often an event is sent to the output
period: ${PERIOD:60s}
twitter:
Defines the catched usernames (screennames)
names: ${SCREEN_NAMES:["@buehler_c", "@smartive_ch", "@iamdevloper"]}

Defines the api and consumer key from twitter api
consumer_key: ${CONSUMER_KEY:my_consumer_key}
consumer_secret: ${CONSUMER_SECRET:my_consumer_secret}
access_key: ${ACCESS_KEY:my_acces_key}
access_secret: ${ACCESS_SECRET:my_acces_secret}
```

I think that this problem is due to Proxy because without it, it works. What is the correct configuration in the case of using Proxy?

```
Proxy server url
proxy_url: "http://user:password@proxy:80"
```

Thanks in advance,

Regards

**Comment by buehler** [comment]
Hey @RdrgPorto 
To be honest, I never tried the twitter beat with a proxy.

I need to investigate this error further. Maybe the elastic beat library changed the config behaviour now, so my initialize method crashes.

Cheers

**Comment by rdrgporto** [comment]
Hey again,

I have solved the problem with **"AccessKey was not set in config"** . It was due to compilation with Go. Twitterbeat didn't read configuration's file. 

I have to use **Beats 1.2.0** (I think because of dependencies). If I download the repository Beats from Git, I will download **Beats 5.0.0** and I think there are problems with **Twitterbeat**.

Now, in a machine with **Ubuntu 15.10**, I don't have problems, it works very well, however with a machine **SUSE Linux Enterprise Server 11 SP4** I have problem with certificates. You know anything about how works the certificates?

```
2016/04/27 13:15:01.642139 twitterbeat.go:163: CRIT Non twitterapi error happend: Get https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=%40iamdevloper&trim_user=true: x509: failed to load system roots and no roots provided
2016/04/27 13:15:01.642168 beat.go:178: CRIT Run returned an error: Get https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=%40iamdevloper&trim_user=true: x509: failed to load system roots and no roots provided
2016/04/27 13:15:01.642177 beat.go:183: INFO Cleaning up twitterbeat before shutting down.
2016/04/27 13:15:01.642182 twitterbeat.go:101: INFO Cleanup api)

```

Thanks in advance,

Regards

**Comment by buehler** [comment]
Hey

I guessed the problem lies with the dependencies. I think they updated the way they read the configurations. I need to investigate that (planning this weekend).

As for the certificates I never ran into those errors, maybe the anaconda lib (twitter api in go) does support some certificates. Do you run the whole thing in docker or do you compile it on on this SUSE machine to run it as a service?

Cheers

**Comment by rdrgporto** [comment]
Hey,

Regarding your question, I don't use Docker with TwitterBeat. I have compiled it with Go 1.5.2 in **SUSE Linux Enterprise Server 11 SP4** and **Ubuntu** too.

Now, I have solved the problem with **SUSE Linux Enterprise Server 11 SP4**. I have compiled TwitterBeat with Go 1.6.2 in **Open Suse 13.2** and it works :smile:.

Moreover, I have created another template because I want to have **“tweet.text.raw”**. It is useful because you can see complete tweet.

![1](https://cloud.githubusercontent.com/assets/6654666/14886262/3477c80a-0d50-11e6-836a-fb3433126e3e.png)

If someone wants to have .raw in the fields I have upload a .txt.
- [templatetwitterbeat.txt](https://github.com/buehler/twitterbeat/files/240534/templatetwitterbeat.txt)

Thanks a lot,

Regards

**Comment by buehler** [comment]
Hey @RdrgPorto 
Cool :) well I need to investigate the configuration stuff anyway, thanks for pointing that out :smile:

I would not mind a pull request with your raw field, I really like the idea of it.

If you don't mind the trouble :wink:

Cheers
